version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: sh -c "cd apps/server && npx prisma db push --schema=./prisma/schema.prisma && cd ../.. && npm run dev --workspace=server"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixbay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data:
